services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: suwkevich_bot
      POSTGRES_USER: suwkevich
      POSTGRES_PASSWORD: suwkevich
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"

volumes:
  postgres_data:

